# This is a basic workflow to help you get started with Actions

name: Quarto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: debian:12-slim
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          apt update && apt install curl gdebi-core -y
          apt install fontconfig -y
          curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
          gdebi -n quarto-linux-amd64.deb
          quarto install tinytex

      - name: Create
        run: |
          export PATH="$HOME/.TinyTeX/bin/x86_64-linux:$PATH"
          mkdir -p ~/texmf/tex/latex
          cd ~/texmf/tex/latex
          curl -LO https://ctan.org/tex-archive/macros/latex/contrib/fancyhdr/fancyhdr.sty
          cd -
          quarto render --to pdf
          
      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: |
            ./_book/*.pdf
